config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pins do
  	resources :comments
  	member do
	  	put "like", to: "pins#upvote"
		 end
	end
	
  root "pins#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pin
  belongs_to :user
end

app/models/pin.rb
class Pin < ApplicationRecord
	acts_as_votable
	belongs_to :user
	has_attached_file :image, styles: { medium: "300x300>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 	has_many :pins
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :find_post
	before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
	before_action :comment_owner, only: [:destroy, :edit, :update]

	def create
		@comment = @pin.comments.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.save

		if @comment.save
			redirect_to pin_path(@pin), notice: "Successfully createed new comment"
		else
			render 'new'
		end
	end

	def destroy
		@comment.destroy
		redirect_to pin_path(@pin)
	end

	def edit
	end

	def update
		if @comment.update(params[:comment].permit(:content))
			redirect_to pin_path(@pin)
		else
			render 'edit'
		end
	end


	private

	def find_post
		@pin = Pin.find(params[:pin_id])
	end

	def find_comment
		@comment = @pin.comments.find(params[:id])
	end

	def comment_owner
		unless current_user.id = @comment.user_id
			flash[:notice] = "No Access"
			redirect_to pin_path(@pin)
		end
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin, only: [:show, :edit, :update, :destroy, :upvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def new
		@pin = current_user.pins.build
	end 

	def show
		@comments = Comment.where(pin_id: @pin).order("created_at DESC")
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin, notice: "Successfully createed new Pin"
		else 
			render 'new'
		end
	end

	def edit
	  @pin = current_user.pins.find(params[:id])
		rescue ActiveRecord::RecordNotFound
    redirect_to pin_path, notice: "You cannot edit this pin."
	end

	def upvote 
		@pin.upvote_by current_user
		redirect_to pin_path
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "Pin was Successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path, notice: "Pin was Successfully deleted!"
	end

	private

	def pin_params
		params.require(:pin).permit(:title, :description, :image)
	end

	def find_pin
		@pin = Pin.find(params[:id])
		rescue ActiveRecord::RecordNotFound
    redirect_to root_path, notice: "Can't find Pin"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/comments/_comment.html.haml
%h2
	= pluralize(@comments.count, "comment")

- @comments.each do |comment|
	.row
		.col-md-6
			%p= comment.content
		- if comment.user_id == current_user.id
			.col-md-6
				.btn-group.pull-right
					= link_to edit_pin_comment_path(comment.pin, comment), class: "btn btn-default btn-xs" do
						%span.glyphicon.glyphicon-pencil
					= link_to [comment.pin , comment], method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default btn-xs" do
						%span.glyphicon.glyphicon-remove
= render 'comments/commentForm'

app/views/comments/_commentForm.html.haml
= form_for([@pin, @pin.comments.build]) do |f|
	.row
		.col-lg-6
			.input-group
				= f.text_field :content, input_html: {class: 'form-control'}
				.input-group-btn.pull-right
					= f.button :submit, class: "btn btn-default btn-sm" do
						%span.glyphicon.glyphicon-plus

app/views/comments/_form.html.haml
= form_for([@pin, @pin.comments.build]) do |f|
	.row
		.col-lg-6
			.input-group
				= f.text_field :content, input_html: {class: 'form-control'}
				.input-group-btn.pull-right
					= f.button :submit, class: "btn btn-default btn-sm" do
						%span.glyphicon.glyphicon-plus

app/views/comments/edit.html.haml
= form_for([@pin, @comment]) do |f|
	.form-group
		= f.text_area :content, input_html: {class: 'form-control'}
	= f.submit

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Piner
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "Piner", root_path
			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "New Pin", new_pin_path
					%li= link_to "My Account", edit_user_registration_path
					%li= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else 
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", user_session_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
		= yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart:true} do |f|
	- if @pin.errors.any?
		#errors
			%h2
			= pluralize(@pin, errors.count, "error")
			prevented this Pin from saving
			%ul
				- @pin.errors.full_messages.each do |msg|
					%li = msg
	.form-group
		= f.input :image, input_html: {class: 'form-control'}
	.form-group
		= f.input :title, input_html: {class: 'form-control'}
	.form-group
		= f.input :description, input_html: {class: 'form-control'}
	= f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Pin
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.haml
#pins.transitions-enabled
	- if user_signed_in?
		- @pins.each do |pin|
			.box.panel.panel-default
				= link_to (image_tag pin.image.url), pin
				- if pin.title?
					%h2= link_to pin.title, pin
	- else 
		%center.jumbotron
			.h1
				Welcome to Piner! 
			= link_to "Sign Up", new_user_registration_path, class: "btn btn-danger btn-default"

app/views/pins/new.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-primary
			.panel-heading
				%h1 Create A New Pin
			.panel-body
				= render 'form'

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col.md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url(:medium)
			.panel-body
				%h1= @pin.title
				%p= @pin.description
			.panel-footer
				.row
					.col-md-6
					= render "comments/comment"
					.col-md-6
						%p.user
						Submitted by
						= @pin.user.email
					.col-md-6
						.btn-group.pull-right
							.like-button.col-sm-3
								= link_to like_pin_path(@pin), method: :put, class: "btn btn-default" do
									%span.glyphicon.glyphicon-heart
										= @pin.get_upvotes.size
							- if current_user.id == @pin.user.id
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-default"
								= link_to "View Original", @pin.image.url(:original, false),class: "btn btn-default"